version: '4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - .:/var/www/lj.aftaa.ru
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/lj.aftaa.ru
